text_chondryty = """Mając ponad 4,5 miliarda lat, **chondryty** są jednymi z najbardziej prymitywnych i dziewiczych skał w Układzie Słonecznym i nigdy nie zostały stopione.
Chondryty mają charakterystyczny wygląd, wykonane z kropelek minerałów krzemianowych zmieszanych z drobnymi ziarnami siarczków i metalu żelazowo-niklowego. Ich milimetrowe granulki nadają chondrytom ich nazwę, od greckiego "chondres" oznaczającego ziarna piasku.
Istnieje wiele odmian chondrytu, z różnicami w mineralogii związanymi z typem asteroidy, z której pochodził meteoryt.
Chondryty to materiał, z którego uformował się Układ Słoneczny. Uległy one niewielkim zmianom w porównaniu ze skałami z większych planet, które zostały poddane aktywności geologicznej. Chondryty mogą nam wiele powiedzieć o tym, jak powstał Układ Słoneczny. 82% procent spadających meteorytów to chondryty."""

text_chondryty_zwyczajne = """**Chondryty zwyczajne** - grupa meteorytów kamiennych należąca do chondrytów. Stanowią ok. 80% wszystkich znajdowanych meteorytów. Chondryty zwyczajne dzielą się na trzy grupy: chondryty oliwinowo-bronzytowe (H), chondryty oliwinowo-hiperstenowe (L), chondryty oliwinowo-pigeonitowe (LL, nazywane też amfoterytami). Chondryty zwyczajne zawierają w swym składzie: piroksen rombowy 20-30%, plagioklaz 5-10%, troilit ok. 5%. Poza tym posiadają również oliwin, kamacyt i taenit w proporcjach zależnych od typu chondrytu. Nie zawierają minerałów z grupą wodorotlenową OH."""

text_chondryty_enstatytowe = """**Chondryty enstatytowe** - grupa meteorytów kamiennych. Jest to najrzadziej spotykany typ meteorytów kamiennych oznaczonych symbolem E. W chondrytach enstatytowych występuje żelazo w postaci metalicznej (kamacyt) i w połączeniu z siarką tworząc troilit (FeS, siarczek żelaza). W meteorytach tych występuje: enstatyt, minerał krzemianowy z magnezowej grupy piroksenów MgSiO3. Może on tworzyć wyraźnie zarysowane struktury chondr enstatytowych. Poza tym w meteorytach tych występują: kwarc, trydymit, krystobalit. Brak w nim natomiast oliwinu oraz krzemianowych minerałów zawierających żelazo.
Pierwszym meteorytem opisanym z tej grupy, był meteoryt spadły w 1901 roku w południowo-zachodniej Finlandii. Jak dotąd największym chondrytem enstatytowym jest kanadyjski meteoryt Abee."""

text_chondryty_węgliste = """**Chondryty węgliste** - grupa meteorytów kamiennych o symbolu ogólnym C. Charakteryzują się bardzo kruchą budową i dlatego przeważnie rozpadają się w trakcie przelotu przez ziemską atmosferę. Dotyczy to głównie grupy C1 i C2. Chondryty węgliste zawierają dużo węgla, do ok. 4% oraz dużo wody, do ok. 20%. Poza tym zawierają krzemiany z grupą wodorotlenową OH i magnetyt (do 25%).
Po raz pierwszy analizie chemicznej poddano chondryt węglisty w 1834 roku. Najbardziej znanym chondrytem węglistym jest meksykański meteoryt Allende."""

text_kakangari_type = """Trzy chondryty tworzą tak zwaną **grupę K (typu Kakangari)**: Kakangari, LEW 87232 i Lea Co. 02. Charakteryzują się dużą ilością pyłowej matrycy i składem izotopów tlenu podobnym do chondrytów węglowych, silnie zredukowanym składem mineralnym i wysoką zawartość metali (6-10% objętościowo), które najbardziej przypominają chondryty enstatytowe, oraz stężenia ogniotrwałych pierwiastków litofilowych, które najbardziej przypominają zwykłe chondryty.
Wiele innych ich cech jest podobnych do chondrytów O, E i C."""

text_rumurutiites = """**Chondryty typu Rumuruti (R)** są bardzo rzadką grupą, z tylko jednym udokumentowanym uderzeniem z prawie 900 udokumentowanych spadków chondrytów. Mają wiele właściwości wspólnych ze zwykłymi chondrytami, w tym podobne typy chondr, kilka wtrąceń ogniotrwałych, podobny skład chemiczny większości pierwiastków oraz fakt, że stosunki 17O/16O są nienormalnie wysokie w porównaniu ze skałami ziemskimi. Istnieją jednak znaczące różnice między chondrytami R a zwykłymi chondrytami: chondryty R mają znacznie więcej pylącego materiału matrycy (około 50% skały), są znacznie bardziej utlenione i zawierają niewielką ilość metalicznego Fe-Ni; a ich wzbogacenie jest wyższe o 170 niż w przypadku zwykłych chondrytów. Prawie cały metal zawarty w nich jest utleniony lub w postaci siarczków. Zawierają mniej chondr niż chondryty E i wydają się pochodzić z regolitu asteroidy."""

text_chondryty_h = """**Chondryty H** to podgrupa chondrytów zwyczajnych, charakteryzująca się wyższą zawartością metalu (12 do 21% żelaza metalicznego) (zwane także chondrytami brązu) 31,4% upadków. Minerały: oliwin, piroksen, metal, plagioklaz, siarczek."""

text_chondryty_l = """**Chondryty L** to kolejna podgrupa chondrytów zwyczajnych, ze średnią zawartością metalu (5 do 10% żelaza metalicznego) (zwane także chondrytami hiperstenowymi) 34,8% upadków. Minerały: oliwin, piroksen, plagioklaz, metal, siarczek."""

text_chondryty_ll = """**Chondryty LL** to trzecia podgrupa chondrytów zwyczajnych, z niską zawartością metalu (około 2% metalicznego żelaza) (zwanych także amfoterytami). Podstawowymi minerałami są bronzyt, oliwin i mniejsze oligoklazy. 7,2% upadków."""

text_achondryty = """**Achondryt** to kamienny meteoryt, który nie zawiera chondr. Składa się z materiału podobnego do ziemskich bazaltów lub skał plutonicznych i został w mniejszym lub większym stopniu zróżnicowany i ponownie przetworzony w wyniku topnienia i rekrystalizacji na ciałach macierzystych meteorytów lub w ich obrębie. W rezultacie achondryty mają odrębną teksturę i mineralogię wskazującą na procesy magmowe.
Achondryty stanowią około 8% wszystkich meteorytów, a większość (około dwie trzecie) z nich to meteoryty HED, prawdopodobnie pochodzące ze skorupy asteroidy 4 Westa. Inne typy obejmują marsjańskie, księżycowe i kilka typów, które prawdopodobnie pochodzą z jeszcze niezidentyfikowanych asteroid."""

text_howardites = """**Howardity** to rodzaj achondrytów z grupy HED, uważanych za pochodzące z asteroidy Westa. Znanych jest około 200 różnych obiektów."""

text_eucrites = """**Eukryty** to achondrytyczne meteoryty kamienne, z których wiele pochodzi z powierzchni asteroidy 4 Westa i należy do klanu meteorytów HED. Są najczęstszą grupą achondrytów, w której znaleziono ponad 100 meteorytów.
Eukryt składa się ze skał bazaltowych ze skorupy 4 Westy lub podobnego ciała macierzystego. Składają się głównie z ubogiego w wapń piroksenu, gołębi i bogatego w wapń plagioklazu (anortyt)."""

text_diogenite = """**Diogenity** - uważa się, że diogenity pochodzą z głębi skorupy asteroidy 4 Westa i jako takie należą do klanu meteorytów HED. Znanych jest około 40 różnych członków.
Diogenity składają się ze skał magmowych pochodzenia plutonowego, które krzepły wystarczająco głęboko w skorupie Westy, tworząc kryształy większe niż w eukrytach. Kryształy te to przede wszystkim ortopiroksen bogaty w magnez z niewielkimi ilościami plagioklazów i oliwinu."""

text_shergottites = """**Szerogity** to grupa meteorytów marsjańskich, pochodzących z Marsa, zawierające skały wulkaniczne. Mniej więcej trzy czwarte wszystkich meteorytów marsjańskich można sklasyfikować jako shergotyty. Ich nazwa pochodzi od meteorytu Shergotty, który spadł w Sherghati w Indiach w 1865 roku. Shergotyty do skał magmowych. Dzielą się na trzy główne grupy: bazaltowe, oliwinowo-firowe (takie jak Tissint znaleziona w Maroku w 2011 r i shergotyty lherzolitowe, w zależności od ich wielkości kryształów i zawartości minerałów. Można je alternatywnie zastosować na trzy lub cztery grupy w zależności od zawartości pierwiastków ziem rzadkich.Te dwa systemy wyszukiwania nie pokrywają się ze sobą, co wskazuje na powiązania między szczątkami źródeł i magmami, z których wynikają się shergotyty."""

text_nakhlites = """**Nahklity** to kolejna grupa meteorytów marsjańskich, składająca się głównie z piroksenów i chlorytów. Nachlity zostały nazwane na cześć pierwszego z nich, meteorytu Nakhla, który spadł w El-Nakhla w Aleksandrii w Egipcie w 1911 roku i miał szacunkową masę 10 kg.
Nachlity to skały magmowe bogate w augit, utworzone z magmy bazaltowej w wyniku co najmniej czterech erupcji, które miały miejsce około 90 milionów lat temu. Zawierają kryształy augitu i oliwinu. Wiek ich krystalizacji, porównany z chronologią liczby kraterów w różnych regionach Marsa, sugeruje, że nakhlity utworzyły się na dużej konstrukcji wulkanicznej Tharsis, Elysium lub Syrtis Major Planum.
Wykazano, że nakhlity zostały zalane ciekłą wodą około 620 milionów lat temu i że zostały wyrzucone z Marsa około 10,75 miliona lat temu w wyniku uderzenia asteroidy. Spadli na Ziemię w ciągu ostatnich 10 000 lat."""

text_chassignite = """**Chassignity** to rzadki rodzaj meteorytu marsjańskiego, znany ze swojej unikalnej mineralogii. Pierwszy meteoryt spadł w Chquirey w Haute-Marne we Francji w 1815 r. Znaleziono tylko jeden inny meteoryt, nazwany Northwest Africa (NWA) 2737. NWA 2737 został znaleziony w Maroku w sierpniu 2000 r. przez łowców meteorytów Bruno Fectaya i Carine Bidaut, która nadała mu tymczasową nazwę „Diderot”. Beck wykazał, że jego „mineralogia, chemia pierwiastków głównych i śladowych, a także izotopy tlenu ujawniły jednoznaczne marsjańskie pochodzenie i silne pokrewieństwo z Ch przypisanym”."""

text_lunar = """**Meteoryty księżycowe** to fragmenty Księżyca, dostarczające cennych danych o geologii naszego naturalnego satelity.Większość meteorytów księżycowych jest wyrzucana z Księżyca w wyniku uderzeń, w wyniku których powstają kratery księżycowe o średnicy kilku kilometrów lub mniejszej. Żaden krater źródłowy meteorytów księżycowych nie został zidentyfikowany, chociaż spekuluje się, że wysoce anomalny meteoryt księżycowy Sayh al Uhaymir 169 pochodzi z Krater uderzeniowy Lalande po prawej stronie Księżyca.

Historia narażenia na promieniowanie kosmiczne ustalona na podstawie pomiarów gazów szlachetnych wykazała, że wszystkie meteoryty księżycowe zostały wyrzucone z Księżyca w ciągu ostatnich 20 milionów lat. Większość opuściła Księżyc w ciągu ostatnich 100 000 lat. Po opuszczeniu Księżyca większość meteoroidów księżycowych wchodzi na orbitę wokół Ziemi i ostatecznie ulega ziemskiej grawitacji. Niektóre meteoroidy wyrzucone z Księżyca są wystrzeliwane na orbity wokół Słońca. Te meteoroidy pozostają w kosmosie dłużej, ale ostatecznie przecinają orbitę Ziemi i ląd."""

text_aubrites = """**Aubryty** to grupa meteorytów nazwana na cześć Aubresa, małego meteorytu achondrytowego, który spadł w pobliżu Nyons we Francji w 1836 roku. Składają się głównie z enstatytu ortopiroksenowego i często nazywane są achondrytami enstatytowymi. Ich magmowe pochodzenie odróżnia je od prymitywnych achondrytów enstatytowych i oznacza, że pochodzą z asteroidy.

Aubryty są zazwyczaj jasne i mają brązowawą skorupę. Często mówi się, że mają pochodzenie „księżycowe”."""

text_acapulcoite = """**Akapulkoity** to grupa meteorytów kamienno-żelaznych, zawierających zarówno metal jak i minerały skalne. Zostały nazwane na cześć jedynego okazu w grupie, którego upadek był świadkiem. Meteoryt Acapulca spadł 11 sierpnia 1976 o godzinie 11:00 w pobliżu kolonii El Quemado (16,883°N 99,9°W), niedaleko Acapulco, Guerrero w Meksyku. Miał masę 1914 gramów. Kamień wydobyto 15 minut później z krateru o głębokości 30 centymetrów (12 cali) i był chłodny w dotyku. Po tym odkryciu 52 okazy meteorytów sklasyfikowano jako akapulkoity."""

text_lodranite = """**Lodranity** to meteoryty kamienno-żelazne, różniące się od innych składem chemicznym. Nazwa grupy lodranitu pochodzi od Lodhran w Pakistanie, gdzie okaz typu spadł 1 października 1868 roku o godzinie 14:00. Naoczni świadkowie upadku zgłosili głośny huk, któremu towarzyszyła unosząca się chmura pyłu na wschód od miasta, co doprowadziło do odkrycia i odzyskania meteorytu. „Meteoryt z Lodranu” został po raz pierwszy opisany przez Gustava Tschermaka w 1870 roku. Opisał meteoryt jako „oprócz niklu i żelaza jest to agregaty oliwinowo-brązzytowe tak wyjątkowego rodzaju, że nigdy wcześniej nie znaleziono ich w meteorycie, jedynie przypominających ziemską skałę oliwinową”. George Thurland Prior jako pierwszy zaklasyfikował meteoryt lodran jako jedyny należący do grupy lodranitów. Dostrzegł także bliskie podobieństwa do ureilitów."""

text_ureilites = """**Ureilit** to rzadki rodzaj meteorytu kamiennego, który ma unikalny skład mineralogiczny, bardzo różniący się od innych meteorytów kamiennych. Nazwa tego ciemnoszarego lub brązowawego meteorytu pochodzi od wioski Nowy Urej (cyrylica: Новый Урей) w Mordowii w Rosji, gdzie meteoryt tego typu spadł 4 września 1886 r. Godnymi uwagi ureilitami są Novo Urei i Goalpara, zwane także dla miasta, w którym wylądował (Goalpara, Assam, Indie). W dniu 7 października 2008 r. malutka asteroida 2008 TC3 weszła w ziemską atmosferę i eksplodowała około 37 kilometrów nad Pustynią Nubijską w Sudanie. Fragmenty tej asteroidy odnaleziono w grudniu następnego roku i okazało się, że są to ureility. Naukowcy odkryli aminokwasy w meteorycie 2008 TC3 tam, gdzie się ich nie spodziewano, biorąc pod uwagę wysokie temperatury osiągnięte podczas eksplozji wynoszące około 1000 °C"""

text_angrite = """**Angryty** to rzadka grupa achondrytów składająca się głównie z diopsydu zawierającego Al-Ti, hedenbergitu, oliwinu, anortytu i troilitu z niewielkimi śladami fosforanów i metali. Nazwa grupy pochodzi od meteorytu Angra dos Reis. Są to najstarsze skały magmowe, których wiek krystalizacji wynosi około 4,56 miliarda lat. Angryty dzielą się na dwie główne grupy: angrity hartowane i plutoniczne. Hartowane angrity schładzały się szybko na powierzchni ciała macierzystego Angrite (APB), podczas gdy angrity plutoniczne schładzały się wolniej, głębiej w skorupie. Uważa się, że APB miał rozmiar podobny do asteroidy 4 Westa."""

text_brachinite = """**Brachinity** to grupa meteorytów sklasyfikowanych jako prymitywne achondryty lub achondryty asteroidalne. Podobnie jak wszystkie prymitywne achondryty, mają podobieństwa do chondrytów i achondrytów. Brachinity zawierają od 74 do 98% (obj.) oliwinu.
Nazwa brachinitów pochodzi od meteorytu Brachina, okazu typu tej grupy, którego nazwa pochodzi od Brachina w Australii Południowej.
Brachinity składają się prawie wyłącznie z oliwinu (74-98% objętości). Inne minerały obejmują plagioklaz (6,7 do 12,9%), siarczki żelaza (1,8 do 4,0%), klinopiroksen (1,5 do 8,2%) i ortopiroksen (0 do 2,4%). Minerały śladowe obejmują fosforany i żelazo meteorytowe. Jedynym odstępstwem od chondrytów jest bardzo wysoki stosunek oliwinu do ortopiroksenu."""

text_winonaite = """**Winonaity** to grupa prymitywnych meteorytów achondrytowych. Podobnie jak wszystkie prymitywne achondryty, winonaity mają podobieństwa z chondrytami i achondrytami. Wykazują oznaki metamorfizmu, częściowego przetopienia, brekcjacji i reliktowych chondr. Ich skład chemiczny i mineralogiczny mieści się pomiędzy chondrytami H i E.

Nazwa grupy winonaitów pochodzi od okazu typu, meteorytu Winona. Sama nazwa pochodzi od słowa Winona w Arizonie, gdzie okaz ten znaleziono podczas wykopalisk archeologicznych w wiosce Elden Pueblo w Sinagua we wrześniu 1928 roku."""

text_żelazne = """**Meteoryty żelazne**, zwane także syderytami lub meteorytami żelaznymi, to rodzaj meteorytów składających się głównie ze stopu żelaza i niklu, znanego jako żelazo meteoryczne, które zwykle składa się z dwóch faz mineralnych: kamacytu i taenitu.
Żelazo znalezione w meteorytach żelaznych było jednym z najwcześniejszych źródeł użytecznego żelaza dostępnych dla ludzi ze względu na plastyczność żelaza meteorytowego przed rozwojem wytapiania, które sygnalizowało początek epoki żelaza.
Chociaż są one dość rzadkie w porównaniu z meteorytami kamiennymi i stanowią jedynie około 5,7% obserwowanych upadków, meteoryty żelazne były w przeszłości znacznie nadreprezentowane w kolekcjach meteorytów. Wynika to z kilku czynników:
Łatwo je rozpoznać jako niezwykłe, w przeciwieństwie do kamiennych meteorytów. Współczesne poszukiwania meteorytów na pustyniach i Antarktydzie dają w sumie znacznie bardziej reprezentatywną próbkę meteorytów.
Są dużo bardziej odporne na warunki atmosferyczne.
Mają znacznie większe szanse na przeżycie przedostawania się do atmosfery i są bardziej odporne na wynikającą z nich ablację. Dlatego częściej można je znaleźć w postaci dużych kawałków.
Ze względu na ich metaliczny skład można je znaleźć nawet po zakopaniu za pomocą powierzchniowego sprzętu do wykrywania metali.
Ponieważ są one również gęstsze niż meteoryty kamienne, meteoryty żelazne stanowią również prawie 90% masy wszystkich znanych meteorytów, czyli około 500 ton. Wszystkie największe znane meteoryty są tego typu, w tym największy – meteoryt Hoba."""

text_heksaedryty = """**Heksaedryty** to meteoryty żelazne o strukturze krystalicznej w postaci heksagonalnych kształtów. To strukturalna klasa meteorytów żelaznych. Składają się prawie wyłącznie z kamacytu ze stopu niklu i żelaza i zawierają niższą zawartość niklu niż oktaedryty. Stężenie niklu w heksaedrytach jest zawsze poniżej 5,8%, a rzadko poniżej 5,3%"""

text_oktaedryty = """**Oktaedryty** to meteoryty żelazne o strukturze krystalicznej w postaci ośmiościennej formy.Oktaedryty są najczęstszą klasą strukturalną meteorytów żelaznych. Struktury powstają, ponieważ żelazo meteoryczne ma określone stężenie niklu, które podczas chłodzenia prowadzi do wydzielania kamacytu z taenitu."""

text_ataksyty = """**Ataksyty** to meteoryty żelazne o strukturze krystalicznej, charakteryzujące się brakiem widocznych wzorów strukturalnych. Ataksyty składają się głównie z żelaza meteorytowego, rodzimego metalu występującego w meteorytach, który składa się z mineralnego taenitu z niewielkimi ilościami plessytu, troilitu i mikroskopijnych blaszek kamacytu. Ataksyty to najbardziej bogate w nikiel znane meteoryty; zwykle zawierają ponad 18% niklu."""

text_żelaza_klasyfikacja_chemiczna = """**Meteoryty żelazne**, pod względem klasyfikacji chemicznej, dzieli się na grupy na podstawie zawartości pierwiastków, takich jak nikiel i kobalt. Nowszy schemat klasyfikacji chemicznej oparty na proporcjach pierwiastków śladowych Ga, Ge i Ir dzieli meteoryty żelazne na klasy odpowiadające odrębnym ciałom macierzystym asteroid. Klasyfikacja ta opiera się na diagramach przedstawiających zawartość niklu w funkcji różnych pierwiastków śladowych (np. Ga, Ge i Ir). Różne grupy meteorytów żelaznych pojawiają się jako skupiska punktów danych.

Pierwotnie istniały cztery takie grupy, oznaczone cyframi rzymskimi I, II, III, IV. Gdy dostępnych stało się więcej danych chemicznych, podzielono je, np. Grupę IV podzielono na meteoryty IVA i IVB. Jeszcze później niektóre grupy ponownie się połączyły, gdy odkryto meteoryty pośrednie, m.in. IIIA i IIIB połączono, tworząc meteoryty IIIAB.
Więcej informacji: https://en.wikipedia.org/wiki/Iron_meteorite"""

text_kamiennożelazne = """**Meteoryty kamienno-żelazne** to grupa meteorytów zawierających zarówno metal, jak i minerały skałotwórcze, tworzącą unikalne struktury. Meteoryty żelazne lub syderolity to meteoryty składające się z prawie równych części żelaza meteorytowego i krzemianów. To odróżnia je od meteorytów kamiennych, które składają się głównie z krzemianów, i meteorytów żelaznych, które składają się głównie z żelaza meteorytowego.

Wszystkie meteoryty kamienno-żelazne są zróżnicowane, co oznacza, że wykazują oznaki zmian. Są zatem achondrytami.

Żelazo kamienne dzieli się na mezosyderyty i pallasyty. Pallasyty mają matrycę z żelaza meteorytowego z osadzonymi krzemianami (większość z nich to oliwin). Mezosyderyty to brekcje wykazujące oznaki metamorfizmu. Żelazo meteoryczne występuje w klastach zamiast w matrycy."""

text_pallasyty = """**Pallasyty** to grupa meteorytów kamienno-żelaznych, charakteryzująca się niską zawartością niklu i specyficznym składem mineralnym. To klasa meteorytów kamienno-żelaznych. Występują stosunkowo rzadko i można je rozpoznać po obecności dużych wtrąceń kryształów oliwinu w osnowie żelazoniklowej.

Kryształy te reprezentują materiał płaszcza i jądra zróżnicowanych planetozymali, które zostały zniszczone w wyniku gwałtownych zderzeń podczas wczesnego formowania się Układu Słonecznego."""

text_mezosyderyty = """**Mezosyderyty** to klasa meteorytów kamienno-żelaznych składających się z mniej więcej równych części metalicznego niklu i żelaza oraz krzemianów. Są to brekcje o nieregularnej fakturze; krzemiany i metale występują często w bryłach lub otoczakach, a także w drobnoziarnistych przerostach. Część krzemianowa zawiera oliwin, pirokseny i skaleń bogaty w Ca i ma podobny skład do eukrytów i diogenitów.

Są rzadkim rodzajem meteorytów; od listopada 2014 r. znanych jest tylko 208 (z czego 56 pochodzi z Antarktydy), a tylko 7 z nich to zaobserwowane upadki. Z drugiej strony niektóre mezosyderyty należą do największych znanych meteorytów."""
